# Generated by Django 3.2.3 on 2021-05-31 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consequence', '0002_businessnature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessnature',
            name='impact_per_employees',
            field=models.FloatField(null=True),
        ),
    ]
