# Generated by Django 3.2.3 on 2021-05-31 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consequence', '0005_truelayeraccount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='truelayeraccount',
            old_name='account_number_sor_code',
            new_name='account_number_sort_code',
        ),
    ]
