# Generated by Django 3.2.3 on 2021-06-01 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consequence', '0008_truelayeraccounttransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='truelayeraccounttransaction',
            name='merchant_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
