# Generated by Django 3.2.3 on 2021-06-01 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consequence', '0011_truelayercardtransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrueLayerClassifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_classification', models.CharField(max_length=200, null=True)),
                ('co2e_factor', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrueLayerMerchants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_name', models.CharField(max_length=200, null=True)),
                ('co2e_factor', models.FloatField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='truelayeraccounttransaction',
            name='transaction_classification_primary',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='truelayercardtransaction',
            name='transaction_classification_primary',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
