# Generated by Django 3.2.3 on 2021-06-01 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consequence', '0012_auto_20210602_0028'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TrueLayerClassifications',
            new_name='TrueLayerClassification',
        ),
        migrations.RenameModel(
            old_name='TrueLayerMerchants',
            new_name='TrueLayerMerchant',
        ),
    ]
